Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
     d.build_dir = "."
     d.remains_running = true
     d.has_ssh = true
  end
  config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.ssh.username = "jupyter"
end
