# Singularity bootstrap based on the jupyter-casa docker. 
# We use this on singularity hub, because it currently
# doesn't have enough resources to build casa.
Bootstrap: docker
From: penngwyn/jupytercasa
IncludeCmd: no

%runscript
    echo "Starting Jupyter"
    cd $HOME
    jupyter notebook

%post
    # Remove Juputer user imported from Docker
    sed -i '/jupyter/d' /etc/passwd
    sed -i '/jupyter/d' /etc/shadow

%environment
  unset XDG_RUNTIME_DIR 
