Bootstrap: docker
From: ubuntu:18.04
IncludeCmd: no

%runscript
    echo "Starting Jupyter"
    jupyter notebook

%environment
    export PYTHONPATH="/usr/local/lib/python3.6/dist-packages" 
    export QT_X11_NO_MITSHM=1
    unset XDG_RUNTIME_DIR 

%setup
    # Add jupyter-casa tree to container
    mkdir ${SINGULARITY_ROOTFS}/usr/local/jupyter-casa
    cp -r jupyter python ${SINGULARITY_ROOTFS}/usr/local/jupyter-casa

%post
    # Setup enviroment
    echo deb http://nl.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse >/etc/apt/sources.list
    echo deb http://nl.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse >>/etc/apt/sources.list

    export LC_ALL=C
    apt-get update && apt-get install -y apt-utils debconf-utils && apt-get upgrade -y
    apt-get install -y python3 python3-dev python3-pip libgfortran3 wget
    apt-get install -y iproute2 lsof
    pip3 install -U pip
    /usr/local/bin/pip install matplotlib astropy notebook widgetsnbextension
    jupyter nbextension enable --py widgetsnbextension --sys-prefix
    # Install casa
    /usr/local/bin/pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatools
    /usr/local/bin/pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatasks
    /usr/local/bin/pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casashell
    # carta
    cd /usr/local
    wget https://github.com/CARTAvis/carta/releases/download/v1.2.2/CARTA-v1.2.2-remote.tgz
    apt-get install -y libnss3 libgdk-pixbuf2.0-0 libgtk-3-0 #libx11-xcb1 libxss1 libasound2
    tar zxf CARTA-v1.2.2-remote.tgz
    # Jupyter-casa
    cd /usr/local
    mkdir -p /usr/local/lib/python3.6/dist-packages
    mv jupyter-casa/python/start_casa /usr/local/lib/python3.6/dist-packages/
    cp -r jupyter-casa/jupyter /usr/local/share/
    # Modified casa tasks for Jupyter
    cd /usr/local
    patch lib/python3.6/dist-packages/casatasks/private/task_setjy.py jupyter-casa/python/casa/task_setjy.patch
    #cp jupyter-casa/python/casa/task_setjy.py $workDir/linux64/lib/python2.7
    #cp jupyter-casa/python/casa/casa_stack_manip.py $workDir/linux64/lib/python2.7
    #rm -rf jupyter-casa
