Bootstrap: docker
From: ubuntu:16.04
IncludeCmd: no

%runscript
    echo "Starting Jupyter"
    jupyter notebook

%environment
  export PYTHONPATH="/usr/local/lib/python2.7/dist-packages:/usr/local/casa/linux64/lib/python2.7" 
  export LD_LIBRARY_PATH="/usr/local/casa/linux64/lib"
  export CASAPATH="/usr/local/casa/ linux64"
  export PATH="/usr/local/casa/linux64/bin:$PATH"
  export QT_X11_NO_MITSHM=1
  unset XDG_RUNTIME_DIR 

%post
    # Setup enviroment
    echo deb http://nl.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse >/etc/apt/sources.list
    echo deb http://nl.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse >>/etc/apt/sources.list

    export LC_ALL=C
    apt-get update && apt-get install -y apt-utils debconf-utils && apt-get upgrade -y
    apt-get install -y python2.7 python-dev python-numpy python-matplotlib python-scipy python-pip python-nose python-dbus\
                       build-essential git wget cmake flex bison g++ xvfb
    apt-get install -y libcfitsio-dev libreadline6-dev libncurses5-dev libhdf5-serial-dev libpython3.5-dev libboost-python-dev\
                       libblas-dev liblapacke-dev libfftw3-dev libgsl-dev libcfitsio3-dev wcslib-dev
    apt-get install -y libboost-program-options1.58-dev libboost-filesystem1.58-dev libboost-system1.58-dev libboost-python1.58-dev libboost-thread1.58-dev libboost-regex1.58-dev
    apt-get install -y libqt4-dev pgplot5 libpgsbox-dev openjdk-8-jre libdbus-1-dev libdbus-c++-dev libxml2-dev libxslt1-dev libqwt-dev libxerces-c-dev libsqlite3-dev liblog4cxx-dev 
    apt-get install -y doxygen swig
    apt-get clean
    # We need an older version of libeigen3 for libsakura
    wget http://launchpadlibrarian.net/165141962/libeigen3-dev_3.2.0-8_all.deb
    dpkg -i libeigen3-dev_3.2.0-8_all.deb
    rm libeigen3-dev_3.2.0-8_all.deb

    # install jupyter
    apt-get install -y gfortran build-essential python-numpy-dev
    pip install --upgrade pip
    /usr/local/bin/pip install jupyter
    
    # Dependencies - RPFITS
    wget ftp://ftp.atnf.csiro.au/pub/software/rpfits/rpfits-2.24.tar.gz
    tar zxvf rpfits-2.24.tar.gz  
    cd rpfits/linux64
    make install
    cd ../..
    rm -rf rpfits*
    
    # Dependencies - Googletest
    wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    tar zxvf release-1.7.0.tar.gz
    rm release-1.7.0.tar.gz
  
    # Dependencies - LIBSAKURA
    git clone https://github.com/CARTAvis/libsakura
    ln -s /googletest-release-1.7.0 libsakura/gtest
    mkdir libsakura/build
    cd libsakura/build
    cmake ..
    make
    make apidoc
    make install
    cd ../..
    rm -rf libsakura
    
    # casa data needs git lfs support
    wget https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-linux-amd64-2.3.4.tar.gz
    tar zxvf git-lfs-linux-amd64-2.3.4.tar.gz
    git-lfs-2.3.4/install.sh
    rm -rf git-lfs-2.3.4 git-lfs-linux-amd64-2.3.4.tar.gz

    # Build casa
    export HOST_CPU_CORES=1  # Only use one core, otherwise we run out of memory on SingularityHub
    export CASA_BUILD_TYPE=Release
    export CASA_ARCH=linux64
    export CASA_BRANCH=release/5.1.1
    export workDir=/usr/local/casa
    export CASAPATH="$workDir $CASA_ARCH"

    git clone -b $CASA_BRANCH https://open-bitbucket.nrao.edu/scm/casa/casa.git $workDir
    cd $workDir
    git submodule update --init casacore
    git clone https://open-bitbucket.nrao.edu/scm/casa/casa-asap.git
    git clone --no-checkout https://open-bitbucket.nrao.edu/scm/casa/casa-data.git $workDir/data
    cd data
    git show HEAD:distro | bash
    # cleanup git, saves ~600MB
    rm -rf .git

    # Build casacore
    mkdir $workDir/casacore/build
    cd $workDir/casacore/build
    cmake .. -DCMAKE_BUILD_TYPE=$CASA_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$workDir/$CASA_ARCH -DDATA_DIR=$workDir/data -DUSE_THREADS=ON -DCFITSIO_INCLUDE_DIR=/usr/include/cfitsio -DCXX11=ON -DUSE_FFTW3=ON -DCFITSIO_INCLUDE_DIR=/usr/include -DUseCasacoreNamespace=1 2>&1 | tee cmake.log 
    make -j$HOST_CPU_CORES
    make install
    cd $workDir
    rm -rf casacore    

    # build casa code
    mkdir $workDir/code/build
    cd $workDir/code/build
    mkdir gtest breakpad
    # For some reason automatic download of googletest and breakpad fails on my system
    cd gtest
    wget https://svn.cv.nrao.edu/casa/devel/googletest/googletest-release-1.7.0.tar.gz
    tar zxvf googletest-release-1.7.0.tar.gz
    cd ../breakpad
    wget https://casa.nrao.edu/download/devel/breakpad//breakpad-from-google-160426-patch3.tgz
    tar zxvf breakpad-from-google-160426-patch3.tgz
    cd ..
    cmake .. -DCMAKE_BUILD_TYPE=$CASA_BUILD_TYPE -DINTERACTIVE_ITERATION=1 -DCMAKE_INSTALL_PREFIX=$workDir/$CASA_ARCH 2>&1 | tee cmake.log
    make -j$HOST_CPU_CORES
    cd $workDir
    rm -rf code/build 
    
    # build gcwrap
    mkdir $workDir/gcwrap/build
    cd $workDir/gcwrap/build
    cmake .. -Darch=$CASA_ARCH -DCMAKE_INSTALL_PREFIX=$workDir/$CASA_ARCH -DPYTHON_LIBNAME=2.7 -DCMAKE_BUILD_TYPE=$CASA_BUILD_TYPE -DINTERACTIVE_ITERATION=1 2>&1 | tee cmake.log
    make -j$HOST_CPU_CORES
    cd $workDir
    rm -rf gcWrap
 
    # Build asap
    mkdir $workDir/casa-asap/build
    cd $workDir/casa-asap/build
    cmake .. -Darch=$CASA_ARCH -DCMAKE_INSTALL_PREFIX=$workDir/$CASA_ARCH -DPYTHON_LIBNAME=2.7 -DCMAKE_BUILD_TYPE=$CASA_BUILD_TYPE 2>&1 | tee cmake.log
    make -j$HOST_CPU_CORES
    cd $workDir
    rm -rf casa-asap
    rm -rf code

    # Install jupyter casa wrapper
    cd $workDir
    git clone https://github.com/aardk/jupyter-casa.git
    mkdir -p /usr/local/lib/python2.7/dist-packages
    mv jupyter-casa/python/casapy /usr/local/lib/python2.7/dist-packages/
    cp -r jupyter-casa/jupyter /usr/local/share/
    # Copy fixed casa tasked
    cp jupyter-casa/python/casa/TablePlotTkAgg.py $workDir/linux64/lib/python2.7
    cp jupyter-casa/python/casa/task_setjy.py $workDir/linux64/lib/python2.7
    cp jupyter-casa/python/casa/casa_stack_manip.py $workDir/linux64/lib/python2.7
    rm -rf jupyter-casa

    # Some cleanup TODO: We could remove much more
    apt-get autoremove -y
    apt-get clean
    rm -rf .git
